import type { Metadata } from 'next';
import { Roboto as RobotoFont } from 'next/font/google';

import './globals.css';

const Roboto = RobotoFont({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'ITROCK',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${Roboto.variable} antialiased`}>{children}</body>
    </html>
  );
}
